# Minimal Instance CR — smallest viable configuration.
apiVersion: core.openeverest.io/v1alpha1
kind: Instance
metadata:
  name: my-database-simple
spec:
  providerRef:
    name: provider-cassandra
  version: "5.0"
  topology:
    type: singleDatacenter
  components:
    engine:
      type: cassandra
      replicas: 1
      storage:
        size: 10Gi
